Repository catze-labs/aptoplay-web, pull requests merged in 2023-02, with the labels that each got.

#11 Add TextInput Component
  components/TextInput.stories.tsx
  components/TextInput.tsx
  package.json
  yarn.lock
Labels: components

#34 Add UI of Footer
  components/Footer.tsx
  components/Layout.tsx
Labels: UI

#36 Add instruction 5, 5-1 markdown
  public/docs/5-1_getGameStatisticsForNFTMetadata.md
  public/docs/5_getGameStatisticsForNFTMetadata copy.md
Labels: documentation
